forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs/apt", "1.8.0"
mod "puppetlabs/concat", "4.0.1"
mod "puppetlabs/mysql", "3.11.0"
mod "puppetlabs/stdlib", "4.19.0"

mod "jippi/nodes-php",
  :git => "https://github.com/jippi/puppet-php.git"
mod "petems-swap_file", "4.0.0"
