def parse_vagrant_config
  require 'yaml'
  config = {}
  
  config_file = File.expand_path(File.join(File.dirname(__FILE__), 'config.yaml'))
  if File.exists?(config_file)
    overrides = YAML.load_file(config_file)
    config.merge!(overrides)
  end
  config
end

Vagrant::Config.run do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.host_name = 'development'
  config.vm.customize ['modifyvm', :id, '--name', 'Joomlatools Development']
  
  v_config = parse_vagrant_config
  
  if v_config.has_key?('hosts')
    v_config['hosts'].each do |host|
      config.vm.network :hostonly, host['ip']
      config.vm.share_folder host['name'], "/var/www/#{host['name']}/source", File.expand_path(host['path'])
    end
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'cookbooks'
    chef.roles_path = 'roles'
    chef.add_role 'default'
  end
end