#
# Author:: Gergo Erdosi (<gergo@timble.net>)
#
# Copyright 2012, Timble CVBA and Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require File.expand_path(File.join(File.dirname(__FILE__), 'config.rb'))

Vagrant::Config.run do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.host_name = 'development'
  config.vm.network :hostonly, '192.168.51.10'
  config.vm.customize ['modifyvm', :id, '--name', 'Joomlatools Development']
  config.vm.customize ['modifyvm', :id, '--memory', 512]
  config.vm.share_folder 'vagrant', '/tmp/vagrant', File.expand_path(File.dirname(__FILE__))
  
  # Load custom configuration file
  v_config = parse_vagrant_config
  
  if v_config.has_key?('hosts')
    v_config['hosts'].each do |host|
      config.vm.share_folder host['name'], "/var/www/#{host['name']}/source", File.expand_path(host['path'])
    end
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'cookbooks'
    chef.roles_path = 'roles'
    chef.add_role 'default'
  end
end