#!/usr/bin/env php
<?php
$autoload = __DIR__.'/vendor/autoload.php';

require_once $autoload;

use Symfony\Component\Console\Application;
use \Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand;

spl_autoload_register(function($className) {
    $className = ltrim($className, '\\');
    $fileName  = __DIR__.'/';

    if ($lastNsPos = strrpos($className, '\\'))
    {
        $namespace = substr($className, 0, $lastNsPos);
        $className = substr($className, $lastNsPos + 1);
        $fileName  .= str_replace('\\', DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
    }

    $fileName .= str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';

    require $fileName;
});

$application = new Application('Joomlatools Box', '0.1');

$application->add(new CompletionCommand());

$application->add(new Command\Apc\Enable());
$application->add(new Command\Apc\Disable());
$application->add(new Command\Apc\Clear());

$application->add(new Command\Xdebug\Enable());
$application->add(new Command\Xdebug\Disable());
$application->add(new Command\Xdebug\Profiler());
$application->add(new Command\Xdebug\Toggle());

$application->add(new Command\Server\Restart());
$application->add(new Command\Server\Start());
$application->add(new Command\Server\Stop());

$application->add(new Command\Php\Ini());
$application->add(new Command\Php\UseVersion());
$application->add(new Command\Php\ListVersion());
$application->add(new Command\Php\Versions());
$application->add(new Command\Php\Remove());
$application->add(new Command\Php\Reset());

$application->add(new Command\Varnish\Enable());
$application->add(new Command\Varnish\Disable());
$application->add(new Command\Varnish\Clear());

$application->add(new Command\Backup());
$application->add(new Command\Restore());

$application->add(new Command\Share());

$application->run();
